### ISSUE TITLE
package is incompatible.

### ISSUE THREAD

**Issue by wangtvb** [openml-labs/gama#171]
1) There are incompatible issues when i install the GAMA  on Google Colab. 
2) when i run the official examples，the data can not be fitted into the model 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
xarray 0.20.2 requires pandas>=1.1, but you have pandas 1.0.5 which is incompatible.
plotnine 0.8.0 requires pandas>=1.1.0, but you have pandas 1.0.5 which is incompatible.
mizani 0.7.3 requires pandas>=1.1.0, but you have pandas 1.0.5 which is incompatible.
google-colab 1.0.0 requires pandas>=1.1.0, but you have pandas 1.0.5 which is incompatible
<img width="1436" alt="Screenshot 2022-08-28 at 23 03 40" src="https://user-images.githubusercontent.com/44760380/187096243-6f81c94f-d7e7-4fd7-b1bd-045ab2a7d8d7.png">
.

**Comment by PGijsbers** [comment]
Thanks for reporting the issue! We are aware of it and [it's already been resolved](https://github.com/openml-labs/gama/issues/152), but we haven't done a release since. We plan for a release soon (early September), until then, you can install gama from github with `python -m pip install git+https://github.com/openml-labs/gama.git`.

**Comment by PGijsbers** [comment]
Should be solved in our new 22.0.0 release. Upgrade gama with `python -m pip install --upgrade gama` or do a fresh install. Please re-open if you find the problem persists.
